apiVersion: v1
kind: Service
metadata:
  name: api-altbank-svc
  namespace: api-altbank
spec:
  type: LoadBalancer
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: api-altbank
